name: Docker Build

on:
  push:
    branches:
      - build-fix

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Image to Registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: |
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/citadel-station-13:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/citadel-station-13:latest
