name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Docker Image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: thakyz/citadel-station-13
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          dockerfile: Dockerfile
          tags: "latest"
          cache: true
